In [1]:
import numpy as np

# 1

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
x1 = np.intersect1d(a, b)
x1

array([2, 4])

# 2 

In [3]:
x2 = np.arange(1,16) #must include 15
x2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x2.reshape(3,5) #reshape into 3 rows and 5 cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
x3 = x2.reshape(3,5).T #transpose the arrays
x3

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# 3

In [6]:
x4 = x3.T #transposeing again would make it easier to flatten
x4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
x4.flatten() #apply the flatten function

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# 4

In [8]:
x3 #2d array used in problem 2

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [9]:
x4 = np.atleast_3d(x3.T) #transformed into 3D array where columns are switched into 1st dimension of 3 dimensions
x4

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15]]])

# 5

In [10]:
x5 = x4.reshape(3,5).T #transform back into 2 dimensional array
x5

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [11]:
#does x3 and x5 match?
np.array_equal(x3, x5)

True

# 6

In [12]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
c = np.intersect1d(a, b) #find common elements
c

array([ 3,  5, 12])

In [13]:
np.asarray([i for i in a if not i in c ]) #from array a choose whatever is in a that is not in the intersection 

array([ 7, 15,  1,  8])

# 7

In [14]:
import pandas

# supress scientific notation np.set_printoptions(suppress = True)
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/atreish/AIM-5001/main/Module6_Data.csv').to_numpy()
type(nyc_water)

numpy.ndarray

What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [15]:
max_watercons = np.max(nyc_water[:,2]) #3rd column index starts at 0
max_watercons

1512.0

How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

In [16]:
np.shape(nyc_water[:,0]) #apply shape function to our ndarry 1st column

(39,)

What is the mean and the standard deviation of the per capita daily water consumption?

In [17]:
mean = np.mean(nyc_water[:,3]) #mean of per capita column
std = np.std(nyc_water[:,3]) #standard deviation of per capita column
print(mean)
print(std)

160.30769230769232
31.51894330370624


What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [18]:
pop_diff = np.diff(nyc_water[:,1], axis=0) #apply to all rows of the 2nd column
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])